### ISSUE TITLE
Making changes to sass styles in host project triggers full page refresh

### ISSUE THREAD

**Issue by mfeckie** [healthsparq/ember-fountainhead#21]
When making styling changes prior to adding fountainhead, styles were updated without triggering full page refresh.

Am I missing a config option?

**Comment by evrowe** [comment]
Off the top of my head I'd guess this is either to do with the way we have handled including fountainhead's CSS into a host app, or something to do with our code that triggers a reload whenever the docs are rebuilt. Docs shouldn't be rebuilt on SCSS changes but it's entirely possible that's what's going on. We will look into it and let you know!

**Comment by DHedgecock** [comment]
This is happening and I think it's worth fixing.

It's happening because we hook into the `preBuild` hook for the addon to call `generateDocs()` whenever the consuming app changes. Unfortunately this hook is also called for css changes. On a CSS change, Fountainhead calls `generateDocs`, then new docs are generated into `/public/docs`. Because Ember watches the public dir, it sees files have changed and reloads the app.

I can't find any docs on unwatching folders, which is a bummer. If we can't find a way to to unwatch part of the public directory, I'm pretty sure we could fix this by generating docs to some folder other than `/public` (like `/docs`) and then using a broccoi Funnel in the `postBuild` hook to pull those generated docs into the build's public directory.

Let's look around a little more for a way to unwatch a directory. If we don't find anything I'll write a Funnel. (This actually might be a good route to go either way, it would probably also resolve the infinite reload issue the first time you build after pulling Fountainhead so we wouldn't have to manually change the .watchmanconfig file in the generator) The only downside is it's another root directory in a consuming app, which some people might not like... but they could just change the output path...

**Comment by DHedgecock** [comment]
Fixed by #22 
Scheduled for 3.0 release. Should be out within the week.
(If you need a short term fix you can set `liveEdit: false` in your fountainhead.js config file to turn off live rebuilding of data files that is causing the page reloads.

Thanks!

**Comment by mfeckie** [comment]
Awesome work :)
