### ISSUE TITLE
"Configuring Fountainhead" link in "Getting Started" guide broken

### ISSUE THREAD

**Issue by dennislaumen** [healthsparq/ember-fountainhead#42]
Hi all!

I was evaluating ember-fountainhead and was reading the guides when I stumbled upon a broken link. On the [Getting Started](https://healthsparq.github.io/ember-fountainhead/guides/getting-started) there's a blue info box which contains a link to [Configuring Fountainhead](https://healthsparq.github.io/guides/configuration). Clicking this link leads me to a GitHub Pages 404.

Hope this helps, keep up the good work!

**Comment by evrowe** [comment]
Whoops! Looks like we have a bad relative URL in one of our guides markdown pages.

(This is a pretty easy one-line fix)[https://github.com/healthsparq/ember-fountainhead/blob/master/guides/getting-started.md] if you're interested in tackling it yourself and helping us keep the docs up to date!

Otherwise we'll make sure to clean that up in the near future. Thanks for filing this issue!

**Comment by dennislaumen** [comment]
Thanks for the pointer @evrowe. I've sent a PR which fixes the link in the GitHub wiki. Assuming this will also fix it on the website, but to be honest I haven't tested this as I know nothing about ember-fountainhead besides the stuff I read on your website an hour ago 😉.
